name: 'IAC generator action'
description: 'Generates IAC opinionated terraform code for your project'
author: 'Thoughtgears'

inputs:
  gcp_project_id:
    description: 'The GCP project ID for your current project'
  service_name:
    description: 'The name of the service you want to deploy'
    required: true

outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: run.js
