name: 'Go test action'
description: 'An action to wrap go binaries in a Javascript SHIM to run it as native action'
author: 'Thoughtgears'

inputs:
  gcp_project_id:
    description: 'The GCP project ID for your current project'
  environment:
    description: 'the environment you are deploying to'
    required: true

outputs:
  gcp_project_id:
    description: 'The GCP project ID for your current project'

runs:
  using: node20
  main: run.js
